// <auto-generated />
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241207182245_migracao1")]
    partial class migracao1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Models.Jogador", b =>
                {
                    b.Property<int>("IdJogador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeIdTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdJogador");

                    b.HasIndex("TimeIdTime");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("API.Models.Time", b =>
                {
                    b.Property<int>("IdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Liga")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTime");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("API.Models.Jogador", b =>
                {
                    b.HasOne("API.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeIdTime");

                    b.Navigation("Time");
                });
#pragma warning restore 612, 618
        }
    }
}
